### ISSUE TITLE
InstanceType property is ignored 

### ISSUE THREAD

**Issue by aquexata** [awslabs/aws-instance-scheduler#130]
Hi,

I'm configuring the schedules and periods with the Instance Scheduler’s AWS CloudFormation custom resource but the InstanceType property that I provide in the period is ignored

Example:

```
AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  ServiceInstanceScheduleServiceToken: 
    Type: String
    Description: ServiceInstanceScheduleServiceToken
Resources:
  DutchOfficehours:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: NL-OfficeHours
      NoStackPrefix: 'True'
      Description: Office hours in NL
      ServiceToken: !Ref ServiceInstanceScheduleServiceToken
      Enforced: 'True'
      Timezone: Europe/Amsterdam
      Periods:
        - Description: Opening hours on weekdays
          BeginTime: '08:00'
          EndTime: '18:00'
          WeekDays: Mon-Fri
          InstanceType: 't3.micro'
```

To workaround  it I've made the next change in `schedule_resource_handler.py`

```
--- source/code/requesthandlers/schedule_resource_handler.py    2019-10-10 16:27:36.281724800 +0100
+++ /tmp/schedule_resource_handler.py   2019-10-11 18:47:16.887958900 +0100
@@ -128,6 +128,7 @@

     def _create_period(self, period):

+        period_temp = period
         self.number_of_periods += 1

         period_name = PERIOD_NAME.format(self._schedule_resource_name, self.number_of_periods)
@@ -159,7 +160,7 @@

         self._logger.info(INF_PERIOD_CREATED, safe_json(period, 3))

-        return period_name, period.get(PROP_INSTANCE_TYPE, None)
+        return period_name, period_temp.get(PROP_INSTANCE_TYPE, None)

     def _delete_periods(self):
         i = 0

```
