### ISSUE TITLE
Add exports to template so can be used by custom resource stacks

### ISSUE THREAD

**Issue by Wade9320** [awslabs/aws-instance-scheduler#188]
When I created some schedules using the custom resources found here: https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-d.html

I was going to have to hard code the arn for the lambda mentioned. I think this could be improved by adding an export to the initial scheduler stack and then this can be referenced in the custom resource like so:

```
Parameters:
  schedulerStack:
    Type: String
    AllowedValues:
    - '<name-of-stack>'
    Default: <name-of-stack>

Resources:
  ukOfficeHours:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: uk-office-hours
      NoStackPrefix: 'True'
      Description: "Office hours in UK"
      ServiceToken:
        Fn::ImportValue: !Sub "${schedulerStack}-${AWS::Region}-InstanceSchedulerMain"
      Timezone: Europe/London
      Metrics: true
      Periods:
        - Description: UK Office Hours
          BeginTime: '08:00'
          EndTime: '17:00'
          WeekDays: Mon-Fri
```

This would be much better than hard coding the arn, as if the lambda changes then you are going to have to change your custom schedule stack/redeploy it.
