### ISSUE TITLE
Not able to start EC2 instances due to License Manager configuration. 

### ISSUE THREAD

**Issue by PrashanthBadaragani** [awslabs/aws-instance-scheduler#213]
Hi All. 

Recently we configured a license manager in our environment, After configuring it, Instance scheduler is not able to star the EC2 instances. we were getting some explicitly permission denied issues but ,there were no such policies with explicitly deny for license manager or EC2 instances.  Even we tried to start the instances manually but it was still the same issue. Once we removed/De register all our EC2 instances from license manager configuration and made it inactive, we were able to start the EC2 instances manually and as well as through Instance scheduler. Could some explain what could be those permission issues and why license manager configuration causing the issue ?

Regards.

**Comment by gockle** [comment]
Hi @PrashanthBadaragani The issue seems to be with AWS License manager configurations, and not related to AWS Instance scheduler solution, please reach out to the AWS Support team for AWS License Manager. Once you are able to manually start/stop EC2 instances, and if the issue still persists with instance scheduler, please let us know and we will take a look.

**Comment by linuxplayground** [comment]
The remote role stack needs to have a resource added.  I added a PR for this today: https://github.com/aws-solutions/aws-instance-scheduler/pull/306

In effect, license-configuration is a required resource type for the StartInstances API call when License Manager is in use.

```
              - Action:
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:ec2:*:${AWS::AccountId}:instance/*"
                  - !Sub "arn:${AWS::Partition}:license-manager:*:${AWS::AccountId}:license-configuration/*"
```
