### ISSUE TITLE
Stop only schedule not working

### ISSUE THREAD

**Issue by mthmi** [awslabs/aws-instance-scheduler#225]
Working with a schedule to stop instances at 6:00PM (18:00) on weekdays and not start them so they had to be manually started and it isn't working.

First attempt was a this schedule that would stop the instances at 18:00, but then start them at 00:00 which is not wanted.
evening-shutdown-1800
endtime 1800
weekdays mon-fri

Second attempt was to take out the weekdays field which I thought would solve the issue with the instances being started at 00:00 but it did not.

Third attempt has been to add a begintime of 18:00 based on advice from AWS support which I thought was working but it turns out it isn't stopping the instances at all and sees they are running and that the desired state is supposed to be stopped but does nothing.

Why don't schedules to stop instances at a set time work? Can someone provide an example of how to shut an instance down at a specific time of day, Mon - Fri without restarting it once it is stopped that works?

**Comment by praveenis** [comment]
Hi,

Create below period and schedule in DynamoDB table '<StackName>-ConfigTable-xxxxxxxx' and Add tag to the EC2 instances Name: 'Schedule' and Value: 'stop-only-schedule'

Period:

{
  "endtime": {
    "S": "18:00"
  },
  "name": {
    "S": "evening-shutdown-1800"
  },
  "type": {
    "S": "period"
  },
  "weekdays": {
    "SS": [
      "mon-fri"
    ]
  }
}

Schedule:

{
  "name": {
    "S": "stop-only-schedule"
  },
  "periods": {
    "SS": [
      "test-period"
    ]
  },
  "timezone": {
    "S": "UTC"
  },
  "type": {
    "S": "schedule"
  }
}

With the above schedule, Instance scheduler will check and stop the instance if the UTC time is equal or greater than the end time specified in the period. If the UTC time is lesser than the end time, the Instance scheduler will do nothing and marks the instance state as 'any' in the DynamoDB '<StackName>-StateTable-xxxxxxx'. Please let us know if the above example schedule meets the requirement.

Note: Instances will not be started by the solution, it will be stopped only on the weekdays at 18:00.

Thanks,
Praveen

**Comment by mthmi** [comment]
What you have listed there is the exact period and schedule I initially tried:

> First attempt was a this schedule that would stop the instances at 18:00, but then start them at 00:00 which is not wanted.
> evening-shutdown-1800
> endtime 1800
> weekdays mon-fri

The weekdays parameter is evaluated as an 'and' condition and the instances are started at 00:00 (midnight) on Monday - Friday.

Testing has proven that to be the case.

**Comment by mpern** [comment]
>Third attempt has been to add a begintime of 18:00 based on advice from AWS support which I thought was working but it turns out it isn't stopping the instances at all and sees they are running and that the desired state is supposed to be stopped but does nothing.

Same problem here. We have a schedule that is supposed to stop instances every day at `23:59`, but it unfortunately does nothing.

Here is the schedule as Cloud Formation resource:

```
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  stopMidnight:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: stopMidnight
      NoStackPrefix: 'True'
      Description: Auto-stop at 23:59
      ServiceToken: >-
        <redacted>
      Enforced: 'False'
      Periods:
        - Description: Stop every day
          EndTime: '23:59'
```
