### ISSUE TITLE
[Doc Info issue] SSM maintenance window parameters clarification. 

### ISSUE THREAD

**Issue by keagansc2** [awslabs/aws-instance-scheduler#232]
Hi there,

From the Appendix D of the scheduler here [1] the custom resource states that the SSM maintenance window can be supplied however, the specific custom resource example contains only the "periods" section. Therefore it is never specified or clarified that the "schedules" section in the custom resource must follow the same behavior. As well within the definition of the parameters that can be passed the actual values needed in the template change, for example in the "Periods" defined parameters value they are supplied as:
=========Periods Doc value vs template value=========
weekdays -> this is the parameter value within the Periods section however, in the template this needs to be supplied as:
WeekDays.
=========Periods Doc value vs template value=========

Therefore for the Custom Resource in Appendix D if one wants to add the SSM Maintenance Window Field how would this be applied to a CFN template?
===============So for example having the doc example:===============
Resources:
  DutchOfficeHours:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
        Name: Tests
        NoStackPrefix: 'True'
        Description: 'Schedule Values'
        ServiceToken: >-
            arn...to..lambda
        Enforced: 'True'
        Timezone: Europe/Amsterdam
        Periods:
          ....
        Schedules:
          - UseMaintenanceWindow: 'False'
            SsmMaintenanceWindow: 'None'
===============So for example having the doc example:===============

The above utilizing the main scheduler (not through CDK but standard CFN) fails with the Main Lambda function returning:
'
Failed to update resource. 
'

From the CloudWatch logs of the function does not give much as returns:
'2021-02-24T09:22:42.267+01:00

Copy
Status code: 200
Status code: 200

2021-02-24T09:22:42.267+01:00

Copy
Status message: 
Status message:

2021-02-24T09:22:43.116+01:00

Copy
END RequestId: 23c8d9cb-5116-45a6-a9f0-40036f48866a
END RequestId: 23c8d9cb-5116-45a6-a9f0-40036f48866a
'

Therefore no real reason as to why. From just testing through the scheduler CLI found that in the arguments for "creating or updating" a scheduler the use_maintenance_window parameter does not want either true or false, it should just be there. Therefore for CloudFormation specification what would that value be?

Please do let me know if you need anymore information.

References:
[1] https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/instance-scheduler.pdf

**Comment by keagansc2** [comment]
quick addition adding stripped down exact template which always fails.
```
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Schedule:
    Type: Custom::ServiceInstanceSchedule
    Properties:
      Name: 'myservice'
      NoStackPrefix: 'False'
      Hibernate: 'False'
      Description: 'adding SsmMaintenanceWindow'
      ServiceToken: 'lambdaARN....'
      Enforced: 'False'
      Timezone: Europe/Berlin
      Periods:
      - Description: 'Daily stop at 18:00'
        EndTime: '18:00'
        WeekDays: 'Mon-Sun'
        Months: 'jan-dec'
      Schedules:
      - UseMaintenanceWindow: 'True'
        SsmMaintenanceWindow: 'None'
```

How can the "Schedules be added to have the SSM property added?
