### ISSUE TITLE
override_status

### ISSUE THREAD

**Issue by ssoto2** [awslabs/aws-instance-scheduler#32]
setting override_status is not clear on usage or not working with a cloudformation schedules. 

I am adding in schedules/periods via cloudformation. I recently have come to the need of using override_status but whenever override_status is used the change set will fail. I think i found a work around by just not setting a start time for the period that is attached to the schedule and not adding override_status but it would be nice to know how to use, but even after re-reviewing the the document i am not seeing any more detail about how override status should work.

**Comment by arieleeuw** [comment]
When setting the override option, which is a schedule level option, instances in the schedule will always be started/stopped independent on whatever periods are defined for that schedule. It's main purpose it to temporary overwrite periods to keep instances running/stopped, without deleting or modifying any of the periods for that schedule. Another use case is to have a group of instances that can be simultaneously by setting the value of the override flag

**Comment by ssoto2** [comment]
@arieleeuw i appreciate you following up but dont think that you are following my concern. I am attempt to run in a schedule like the following:

```yaml
 AWSTemplateFormatVersion: "2010-09-09"
Description: "Builds out Schedule Rules for Alpha Cluster Instances to Follow"
Resources:
  AlphaHours:
    Type: "Custom::ServiceInstanceSchedule"
    Properties:
      Description: "Times For Alpha Cluster Boxes"
      ServiceToken: "arn:aws:lambda:us-east-1:REMOVED:function:InstanceSchedule-InstanceSchedulerMain"
      Timezone: "US/Eastern"
      override_status: "stopped"
      Periods:
        - Description: "Running Hours Weekdays"
          BeginTime: "07:00"
          EndTime: "19:00"
          WeekDays: "Mon-Fri"
```

The cloud formation schedule above will fail in cloudformation every time. Remove override_status and it works perfectly. Additionally if i try other schedule options like enforce they work just when using override_status have i been having this problem

**Comment by arieleeuw** [comment]
Hi I will investigate this issue and let you know as soon as I have a work around or a fix

**Comment by arieleeuw** [comment]
The Name of the property to use is **OverrideStatus** (all properties are in PascalCase)

Below is an example of a template that should work.

Hope this helps

Arie

```
AWSTemplateFormatVersion: 2010-09-09
Description: BMC Schedules
Resources:
  AlphaHours:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      ServiceToken: >-
        arn:aws:lambda:us-east-1: REMOVED:function:InstanceScheduler-InstanceSchedulerMain
      Description: Times For Alpha Cluster Boxes
      Timezone: US/Eastern
      OverrideStatus: stopped
      Periods:
        - Description: Running Hours Weekdays
          BeginTime: '07:00'
          EndTime: '19:00'
          WeekDays: Mon-Fri
```
